/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package devop;

import com.sun.jdi.connect.spi.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.DriverManager;

//import net.proteanit.sql.DbUtils ;

import java.sql.PreparedStatement;

import javax.swing.JOptionPane;

/**
 *
 * @author 21Aud
 */
public class cuisine extends javax.swing.JFrame {

    
    /**
     * Creates new form cuisine
     */
    public cuisine() {
        initComponents();
    }
    String driver ="com.mysql.cj.jdbc.Driver";
    String url="jdbc:mysql://localhost:3306/cuisine?zeroDateTimeBehavior=CONVERT_TO_NULL";
    String user="root";
    String password="";
    
   ResultSet rs;
   Statement st;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Recette = new javax.swing.JLabel();
        recette_id = new javax.swing.JLabel();
        recette_name = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        Create = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Read = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ingredient = new javax.swing.JLabel();
        ingredient_id = new javax.swing.JLabel();
        ingredient_recette_id = new javax.swing.JLabel();
        ingredient_nom1 = new javax.swing.JLabel();
        ingredient_nom2 = new javax.swing.JLabel();
        ingredient_nom3 = new javax.swing.JLabel();
        ingredient_nom4 = new javax.swing.JLabel();
        ingredientId = new javax.swing.JTextField();
        nom4 = new javax.swing.JTextField();
        nom3 = new javax.swing.JTextField();
        nom2 = new javax.swing.JTextField();
        nom1 = new javax.swing.JTextField();
        ingredientRecetteId = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        CreateIngredient = new javax.swing.JButton();
        UpdateIngredient = new javax.swing.JButton();
        DeleteIngredient = new javax.swing.JButton();
        ReadIngredient = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Recette.setText("RECETTES");

        recette_id.setText("recette_id");

        recette_name.setText("recette_name");

        Create.setBackground(new java.awt.Color(51, 255, 0));
        Create.setText("Create");
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });

        Delete.setBackground(new java.awt.Color(255, 0, 0));
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Update.setBackground(new java.awt.Color(255, 255, 51));
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Read.setBackground(new java.awt.Color(51, 102, 255));
        Read.setText("Read");
        Read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "recette_id", "recette_name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Byte.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        ingredient.setText("INGREDIENTS");

        ingredient_id.setText("Id");

        ingredient_recette_id.setText("recette_id");

        ingredient_nom1.setText("nom_ingredient1");

        ingredient_nom2.setText("nom_ingredient2");

        ingredient_nom3.setText("nom_ingredient3");

        ingredient_nom4.setText("nom_ingredient4");

        nom4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom4ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        CreateIngredient.setBackground(new java.awt.Color(0, 255, 0));
        CreateIngredient.setText("Create");
        CreateIngredient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateIngredientActionPerformed(evt);
            }
        });

        UpdateIngredient.setBackground(new java.awt.Color(255, 255, 51));
        UpdateIngredient.setText("Update");
        UpdateIngredient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateIngredientActionPerformed(evt);
            }
        });

        DeleteIngredient.setBackground(new java.awt.Color(255, 0, 0));
        DeleteIngredient.setText("Delete");
        DeleteIngredient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteIngredientActionPerformed(evt);
            }
        });

        ReadIngredient.setBackground(new java.awt.Color(0, 51, 255));
        ReadIngredient.setText("Read");
        ReadIngredient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadIngredientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ingredient, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Delete)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Recette, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(recette_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(recette_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(Create))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                            .addComponent(id)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Update)
                                            .addComponent(Read))))
                                .addGap(83, 83, 83)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ingredient_nom4)
                                .addGap(18, 18, 18)
                                .addComponent(nom4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ingredient_nom1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nom1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ingredient_nom2)
                                .addGap(18, 18, 18)
                                .addComponent(nom2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ingredient_nom3)
                                .addGap(18, 18, 18)
                                .addComponent(nom3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ingredient_id, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ingredient_recette_id, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ingredientRecetteId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ingredientId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CreateIngredient)
                        .addGap(18, 18, 18)
                        .addComponent(UpdateIngredient)
                        .addGap(33, 33, 33)
                        .addComponent(DeleteIngredient)
                        .addGap(32, 32, 32)
                        .addComponent(ReadIngredient)))
                .addContainerGap(684, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Recette)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(recette_id, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(recette_name, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Create)
                            .addComponent(Read))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Delete)
                            .addComponent(Update))
                        .addGap(70, 70, 70)
                        .addComponent(ingredient)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ingredient_id)
                            .addComponent(ingredientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ingredient_recette_id)
                            .addComponent(ingredientRecetteId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ingredient_nom1)
                            .addComponent(nom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ingredient_nom2)
                            .addComponent(nom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ingredient_nom3)
                            .addComponent(nom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ingredient_nom4)
                            .addComponent(nom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CreateIngredient)
                            .addComponent(UpdateIngredient)
                            .addComponent(DeleteIngredient)
                            .addComponent(ReadIngredient))))
                .addContainerGap(737, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
        // TODO add your handling code here:
        
        try{
            
            Class.forName(driver);
            
            java.sql.Connection con = DriverManager.getConnection(url, user, password);
           // Connection con = (Connection) DriverManager.getConnection(url, user, password);
            String sql ="insert into recette values('"+id.getText()+"','"+name.getText()+"')";
            st = con.createStatement();
            st.execute(sql);
            
            JOptionPane.showMessageDialog(this, "Create Sussessfully");
        }
        
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_CreateActionPerformed

    private void ReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadActionPerformed
        // TODO add your handling code here:
         try{
            
            Class.forName(driver);
            
            java.sql.Connection con = DriverManager.getConnection(url, user, password);
           // Connection con = (Connection) DriverManager.getConnection(url, user, password);
            String sql ="select * from recette ";
            st = con.createStatement();
            st.execute(sql);
            
            jTable1.setModel (DbUtils.resultSetToTableModel(rs));
        }
        
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_ReadActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        
         try{
            
            Class.forName(driver);
            
            java.sql.Connection con = DriverManager.getConnection(url, user, password);
           // Connection con = (Connection) DriverManager.getConnection(url, user, password);
            String sql ="update recette set recette_name ='"+name.getText()+"'where  recette_id ='"+id.getText()+"' ";
            st = con.createStatement();
            st.execute(sql);
            
            JOptionPane.showMessageDialog(this, "Update Sussessfully");
        }
        
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        
         try{
            
            Class.forName(driver);
            
            java.sql.Connection con = DriverManager.getConnection(url, user, password);
           // Connection con = (Connection) DriverManager.getConnection(url, user, password);
            String sql ="delete from recette where recette_id = '"+id.getText()+"' ";
            st = con.createStatement();
            st.execute(sql);
            
            JOptionPane.showMessageDialog(this, "Delete Sussessfully");
        }
        
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void nom4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom4ActionPerformed

    private void CreateIngredientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateIngredientActionPerformed
        // TODO add your handling code here:
         try{
            
            Class.forName(driver);
            
            java.sql.Connection con = DriverManager.getConnection(url, user, password);
           // Connection con = (Connection) DriverManager.getConnection(url, user, password);
            String sql ="insert into ingredient values('"+ingredientId.getText()+"','"+ingredientRecetteId.getText()+"','"+nom1.getText()+"', '"+nom2.getText()+"', '"+nom3.getText()+"', '"+nom4.getText()+"')";
            st = con.createStatement();
            st.execute(sql);
            
            JOptionPane.showMessageDialog(this, "Create Sussessfully");
        }
        
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
  
    
     
    }//GEN-LAST:event_CreateIngredientActionPerformed

    private void DeleteIngredientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteIngredientActionPerformed
        // TODO add your handling code here:
         try{
            
            Class.forName(driver);
            
            java.sql.Connection con = DriverManager.getConnection(url, user, password);
           // Connection con = (Connection) DriverManager.getConnection(url, user, password);
            String sql ="delete from ingredient where id = '"+ingredientId.getText()+"' ";
            st = con.createStatement();
            st.execute(sql);
            
            JOptionPane.showMessageDialog(this, "Delete Sussessfully");
        }
        
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_DeleteIngredientActionPerformed

    private void UpdateIngredientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateIngredientActionPerformed
        // TODO add your handling code here:
           try{
            
            Class.forName(driver);
            
            java.sql.Connection con = DriverManager.getConnection(url, user, password);
           // Connection con = (Connection) DriverManager.getConnection(url, user, password);
            String sql ="update ingredient set recette_id ='"+ingredientRecetteId.getText()+"', nom_ingredient1 ='"+nom1.getText()+"',nom_ingredient2 ='"+nom2.getText()+"',nom_ingredient3 ='"+nom3.getText()+"',nom_ingredient4 ='"+nom4.getText()+"' where  id ='"+ingredientId.getText()+"' ";
            st = con.createStatement();
            st.execute(sql);
            
            JOptionPane.showMessageDialog(this, "Update Sussessfully");
        }
        
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_UpdateIngredientActionPerformed

    private void ReadIngredientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadIngredientActionPerformed
        // TODO add your handling code here:
         try{
            
            Class.forName(driver);
            
            java.sql.Connection con = DriverManager.getConnection(url, user, password);
           // Connection con = (Connection) DriverManager.getConnection(url, user, password);
            String sql ="select * from ingredient ";
            st = con.createStatement();
            st.execute(sql);
            
            jTable1.setModel (DbUtils.resultSetToTableModel(rs));
        }
        
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_ReadIngredientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cuisine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cuisine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cuisine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cuisine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cuisine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Create;
    private javax.swing.JButton CreateIngredient;
    private javax.swing.JButton Delete;
    private javax.swing.JButton DeleteIngredient;
    private javax.swing.JButton Read;
    private javax.swing.JButton ReadIngredient;
    private javax.swing.JLabel Recette;
    private javax.swing.JButton Update;
    private javax.swing.JButton UpdateIngredient;
    private javax.swing.JTextField id;
    private javax.swing.JLabel ingredient;
    private javax.swing.JTextField ingredientId;
    private javax.swing.JTextField ingredientRecetteId;
    private javax.swing.JLabel ingredient_id;
    private javax.swing.JLabel ingredient_nom1;
    private javax.swing.JLabel ingredient_nom2;
    private javax.swing.JLabel ingredient_nom3;
    private javax.swing.JLabel ingredient_nom4;
    private javax.swing.JLabel ingredient_recette_id;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nom1;
    private javax.swing.JTextField nom2;
    private javax.swing.JTextField nom3;
    private javax.swing.JTextField nom4;
    private javax.swing.JLabel recette_id;
    private javax.swing.JLabel recette_name;
    // End of variables declaration//GEN-END:variables

   
}
